export { authAPI } from './auth';
export { projectAPI } from './projects';
export { boardAPI } from './boards';
export { issueAPI } from './issues';
export { sprintAPI } from './sprints';
export { formsAPI } from './forms';
export { pagesAPI } from './pages';
export { usersAPI } from './users';
export { labelAPI } from './labels';
export { default as client } from './client';
